### ISSUE TITLE
事務局員管理アプリのモデルに部局を追加する

### ISSUE THREAD

**Issue by kkiyama117** [NovemberFestival/NotFlaw#72]
- # 部局モデルの追加と登録
> - 本部
> - おま・模擬
> - おま・グラ
> - おま・ステ
> - おま・企画室
> - 渉外
> - 広報
> - パンフ
> - 総対
> - 自セ
> - 会計 

# 事務局員に部局の設定をする
> `fields.foreignkey` あたりかな？

**Comment by kkiyama117** [comment]
@ZuyaGH commit のコメントに #72 を打ってないよーん

**Comment by ZuyaGH** [comment]
適当にコメントを入れて#72を挿入してCommitし直しました。

**Comment by kkiyama117** [comment]
おｋまる。
